### ISSUE TITLE
Extracting model predictions (@eta) from lmerMod objects

### ISSUE THREAD

**Issue by andkov** [andkov/Multilevel-models-of-NLSY-97-religion-data#1]
Open repository
Run
"1.ISE-NLSY97-Religion.R"
This will produce the data and run the first model, creating an lmer object.
Now we want to extract the model predictions form in.
In the "3.plotting lmer results in ggplot2.R" lines 21-26 are supposed to do that but throw an error
Error in data.frame(model@flist, timec = model@X[, 2], YHat = model@eta) : 
  no slot of name "X" for this object of class "lmerMod"

This is strange, because it used to work. 
Any thought what might be the matter?

**Comment by wibeasley** [comment]
Can you paste or link to the code?  My first suspect with lme4 is making sure I made the variable a factor.

**Comment by andkov** [comment]
https://github.com/andkov/Multilevel-models-of-NLSY-97-religion-data/blob/master/3.plotting%20lmer%20results%20in%20ggplot2.R

lines 21-26

**Comment by andkov** [comment]
this (https://github.com/andkov/Multilevel-models-of-NLSY-97-religion-data/commit/61911dee9adff5e31a3e356b2481cd78e214a322) is an attempt at a work around, but i'm not sure what i'm doing here, really

**Comment by wibeasley** [comment]
I think it's done/resolved.  Reopen if not.
